name: Build
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        name: Install pnpm
      - name: Install Node.js
        uses: actions/setup-node@v4
      - name: Install dependencies
        run: corepack enable && pnpm install
      - name: Build
        run: pnpm run build
      - name: Package
        run: pnpm version 0.0.$(date +'%y%m%d%H%M%S') --no-git-tag-version && pnpm pack
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: "*.tgz"
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          version="$(node -p "require('./package.json').version")"
          gh release create "v$version" --title "v$version" --notes "Automated release for version $version" *.tgz
